// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma

const { defineConfig } = require("prisma/config");
require("dotenv").config({ path: "./config/config.env" });

module.exports = defineConfig({
  schema: "prisma/schema.prisma",
  datasource: {
    url: process.env.DATABASE_URL, // This pulls from your .env file
  },
});

// import "dotenv/config";
// import { defineConfig } from "prisma/config";

// export default defineConfig({
//   schema: "prisma/schema.prisma",
//   migrations: {
//     path: "prisma/migrations",
//   },
//   datasource: {
//     url: process.env["DATABASE_URL"],
//   },
// });
